apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fqw2odwd2-python
  janus-idp.io/tekton: fqw2odwd2-python
  backstage.io/kubernetes-id: fqw2odwd2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fqw2odwd2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
